### PR TITLE
The new capability added - generate names of random persons

### PR DESCRIPTION
**Pull request by it-praktyk**
I've added the new capability for your module. Using `[person]` template you can generate names of random persons based on culture - currently only en-US - and sex.

### CODE REVIEW

**Comment by dfinke** [comment]
Awesome! 

What are your thoughts of making this change?

from
`Invoke-Generate "[person]" -Sex female -count 5`
to
`Invoke-Generate "[person female]" -count 5`
`Invoke-Generate "[person male]" -count 5`

**Comment by dfinke** [comment]
Actually, the second version syntax does work.

Please recheck your `if`, you use a `=`  for comparison and in the `elseif` you compare the wrong variable.

```
If ($Sex -eq "both") {
    $FirstName = $AllNames[(Get-Random -Minimum 0 -Maximum ($AllNamesCount - 1))].(Get-Random @('FemaleFirstName', 'MaleFirstName'))
} elseif ($Sex -eq "female") {
    $FirstName = $AllNames[(Get-Random -Minimum 0 -Maximum ($AllNamesCount - 1))].FemaleFirstName
} else {
    $FirstName = $AllNames[(Get-Random -Minimum 0 -Maximum ($AllNamesCount - 1))].MaleFirstName
}
```

**Comment by it-praktyk** [comment]
Thanks to find my mistakes, the next time I'll wait for opening a pull request until morning. 

I've implemented the change proposed by you.

I've reformatted and cleaned a code also a bit - I've clicked 'Format script' in Sapien PowerShell Studio - and replaced used aliases. Now PSScriptAnalyzer show the only one warning.

Under the New-RandomPerson https://github.com/it-praktyk/New-RandomPerson I'll expand my idea - I'll use it to fulfill Active Directory/Exchange labs.

**Comment by dfinke** [comment]
Thanks for the updates. It's often good to do a PR early, so reviews of the code can kick off. The more eyes on the script the better.

I'll take a look. I need to update my install script to copy the culture directory so whom I publish it to the gallery it all works. 

For bonus points, could you look at my other repos and see how to enable the installing from github?

Thanks for the great feature. 

Doug

**Comment by dfinke** [comment]
Not sure we need the `personmale` `personfemale` this works and is similar to synonym

```
Invoke-Generate "[person male]"

Invoke-Generate "[person female]"
```

**Comment by dfinke** [comment]
I made changes, https://github.com/dfinke/NameIT/commit/a6c6ee8596deddf6315abf0be63723cbe622cfd3

I published the feature to the [PowerShell Gallery](https://www.powershellgallery.com/packages/NameIT/1.04)

Thank you for the feature!

Doug

**Comment by it-praktyk** [comment]
Thank you, I'll update it on evening (I live in Poland, GMT+1).

If you will announce the newer version on Twitter my Twitter account is @ITpraktyk ,

It was fun for me work under that code. Thank you for your remarks and accepting my contribution. 

See you next time :-)

**Comment by dfinke** [comment]
Tweeting it now, was just looking for your twitter handle.

**Pull request merged**
