### PR TITLE
CWDev

### PR DESCRIPTION
**Pull request by merddyin**
Standardize and update several legacy generators, expand several data sets, add two new generators. Creating PR at present for preview of updates.

### CODE REVIEW

**Comment by dfinke** [comment]
Have a look at the tests. If it is too involved to fix, let me know

**Comment by merddyin** [comment]
Ok, so far I've fixed the City generator...mostly, but I'll get to that in a sec.
   
   - Issue: General test failing
   
   - Cause: The ($null -ne $propertyName) wasn't returning true when it should have
   - Fix: Adjusted to ($null -ne $propertyName -or $propertyName -eq "") so default path would fire properly
   
   - Issue: Specified culture of 'sv' test failing
   
   - Cause: I suspect this is because my native culture isn't Sweden, so it failed to fall back to en-US
   - Fix: For the moment, using a try/catch to force an override to en-US in the event that an error pops from the Resolve-LocalizedPath
   - Note: Long-term fix will probably involve forcing an override to en as a third-pass option in Resolve-LocalizedPath
The same two issues exist for any generators that I'm doing an import and property filtering on, so I'm in the process of applying the same fix to those, which brings me to the other issue I encountered, which is more of a core problem.
One of my goals was to avoid repeating code from more simple generators when creating the complex ones by calling on Invoke-Generate to do the work. In fact this will be key for making the [organization] generator work. My expectation was that I would be able to return a PSCustomObject that I could then leverage the properties of to build out the elements of the calling generator. For example, the updated [address] generator calls on the [city] generator, from which it leverages the City, State, County, and PostalCode properties, as well as latitude and longitude if IncludeGeo is used. Only the street address itself is generated within the [address] generator, which mimics the original behavior. 
Unfortunately this isn't working out so well, as it appears that you are currently forcing an override of the return format in the main Invoke-Generate function. I saw the 'AsPSObject' option, but it looks like you are only ever expecting a single string as a return value, so using that just returns a mess. Not sure if I should re-evaluate my approach, or if the Invoke function should be augmented to leave things alone if the generator returns an object. Thoughts?
Chris Whitfield 

    On Monday, April 3, 2023 at 04:07:36 PM CDT, Doug Finke ***@***.***> wrote:  
 
 


Have a look at the tests. If it is too involved to fix, let me know

**Comment by merddyin** [comment]
You can disregard...think I figured out a work around. Determined that I can get the callstack to determine if the generator is being called via Invoke-Generate, and then I can convert the value into a herestring that Invoke can translate when it calls ConvertFrom-StringData. I still think it would be good if Invoke would simply return the object if one is returned from a generator, but I can work around this. I believe I can also directly call a generator from another generator without using Invoke, which I'm testing next.
Chris Whitfield 

    On Tuesday, April 4, 2023 at 01:58:54 PM CDT, Chris Whitfield ***@***.***> wrote:  
 
 Ok, so far I've fixed the City generator...mostly, but I'll get to that in a sec.
   
   - Issue: General test failing
   
   - Cause: The ($null -ne $propertyName) wasn't returning true when it should have
   - Fix: Adjusted to ($null -ne $propertyName -or $propertyName -eq "") so default path would fire properly
   
   - Issue: Specified culture of 'sv' test failing
   
   - Cause: I suspect this is because my native culture isn't Sweden, so it failed to fall back to en-US
   - Fix: For the moment, using a try/catch to force an override to en-US in the event that an error pops from the Resolve-LocalizedPath
   - Note: Long-term fix will probably involve forcing an override to en as a third-pass option in Resolve-LocalizedPath
The same two issues exist for any generators that I'm doing an import and property filtering on, so I'm in the process of applying the same fix to those, which brings me to the other issue I encountered, which is more of a core problem.
One of my goals was to avoid repeating code from more simple generators when creating the complex ones by calling on Invoke-Generate to do the work. In fact this will be key for making the [organization] generator work. My expectation was that I would be able to return a PSCustomObject that I could then leverage the properties of to build out the elements of the calling generator. For example, the updated [address] generator calls on the [city] generator, from which it leverages the City, State, County, and PostalCode properties, as well as latitude and longitude if IncludeGeo is used. Only the street address itself is generated within the [address] generator, which mimics the original behavior. 
Unfortunately this isn't working out so well, as it appears that you are currently forcing an override of the return format in the main Invoke-Generate function. I saw the 'AsPSObject' option, but it looks like you are only ever expecting a single string as a return value, so using that just returns a mess. Not sure if I should re-evaluate my approach, or if the Invoke function should be augmented to leave things alone if the generator returns an object. Thoughts?
Chris Whitfield 

    On Monday, April 3, 2023 at 04:07:36 PM CDT, Doug Finke ***@***.***> wrote:  
 
 


Have a look at the tests. If it is too involved to fix, let me know

**Comment by merddyin** [comment]
I've updated the remaining generators from the legacy set. All should now properly generate the expected legacy value, and all should also now work with output as objects. Only negative is that you must specify '-AsObject' on the generator call _and_ '-AsPSObject' for the Invoke, but this is strictly because of the need to maintain the default legacy behavior. If, at some point, the legacy behavior (simple single string output) is not required, or can be handled using just Invoke, then the object can become the default option and just get converted after output. Once the tests are authorized to run, I'll take a look at any new errors that might crop up. 

As a note, the preview request was less about function, and more about format and intent. I had not completed a full set of functional tests prior to this, which is not how I typically do things...guess I was over-excited. Will be sure to complete my testing prior to upload in future.

**Comment by merddyin** [comment]
Closing PR as part of reset

**Pull request closed without merging**
