### PR TITLE
Extending NameIT PoSh project by adding Afrikaans, only 1 of the 11 official South African languages

### PR DESCRIPTION
**Pull request by Grant-Steinfeld**
Still not sure all is correct, but hey giving it a bash ... (posh :) )

### CODE REVIEW

**Comment by dfinke** [comment]
Check the tests that are failing

**Comment by dfinke** [comment]
Please check your unit tests

**Comment by Grant-Steinfeld** [comment]
Will research the failing tests, thought the seed was indeed set to 0

**Comment by dfinke** [comment]
Can you run the GHA on your fork, then you can speed up the inner feedback loop.

**Comment by Grant-Steinfeld** [comment]
I'll persevere need more time - and also change this up to cover the generalize and aggregate all South African 11 official and unofficial languages

**Pull request closed without merging**
